### PR TITLE
Add new participant

### PR DESCRIPTION
**Pull request by ElenaG518**

### CODE REVIEW

**Comment by ElenaG518** [comment]
@tienyuan -- I cant seem to add you as a reviewer, but this PR adds a second participant into the database

**Comment by tienyuan** [comment]
Hmm, I can't seem to run your version. I'm taking a look

**Comment by tienyuan** [comment]
@ElenaG518 Ok, I copied the jsx files and the seed.sql file over to a new branch and running that went fine. So I chalk up my earlier issues running the code to docker problems.

I'm tagging @serpient to review too since this will merge into her work. 

You can merge after her approval

**Comment by tienyuan** [comment]
Elena, can you reopen another pr with only the seed.sql change? Thanks!

The notes component is already in elsewhere

**Pull request closed without merging**
