### PR TITLE
React integration

### PR DESCRIPTION
**Pull request by serpient**
Create-React-App with SCSS integration

### CODE REVIEW

**Comment by serpient** [comment]
@mitchellwandrews  is this ok for merge? also, will there be a development branch for frontend work or are we merging straight into master branch?

**Comment by mitchellwandrews** [comment]
@serpient should be ok to merge but let's check with @tienyuan we did have a plan to merge on mondays at hack night, but with the extended break and the project still being in the early stages I think it's fine. I started the db tables last night. I have at least a couple more to setup and then build routes for and then we can really start building the front-end. Trying to have that in by Saturday evening. A branch might be a good idea once we have the site more built out.

**Comment by mitchellwandrews** [comment]
@tienyuan We will probably be using a small react app in the intake form app as well so maybe both? I'm not well versed in React so not sure when we want to integrate. I will be diving deeper into React over the break.

**Comment by mitchellwandrews** [comment]
@tienyuan All good! Gina was there and we talked a bit about the possible scenario of a repeat participant and I started building some db schemas.

I think scenario 2 may be the better route and more of a standard practice with React nowadays, but I am also not experienced in React so maybe @serpient can shed some light or ideas? I only have the back-end serving a hello world page so not really losing much there if we throw it out. 

Also agree it may be best to talk about it on the 7th and hash it out. For the time being we can keep the react part in spikes and move it over accordingly after then.

**Comment by tienyuan** [comment]
👍 Yeah scenario 2 is more normal. Scenario 1 would have been an option with less infrastructure. Anyways merging!

**Pull request merged**
